<?php
	$result_code = Mage::registry('result_code');
	$result_msg = Mage::registry('result_msg');
?>
<div id="paymentcc">
	<table align="center">
		<tr>
			<td style="text-align: center;">
				<div id="subtitle" style="text-align: center">
					Code : <?php echo $result_code; ?><br/>
					Message : <?php echo $result_msg; ?>
				</div>
			</td>
		</tr>
	</table>
</div>
<?php
	
?>