<?php
	$js_base_url = Mage::registry('js_base_url');
	$return_base_url = Mage::registry('return_base_url');
	$tXid = Mage::registry('tXid');
?>
<div id="paymentcc">
	<table align="center">
		<tr>
			<td style="text-align: center;">
				<div id="subtitle" style="text-align: center">
					You will be redirected to NICEPay Payment Page in <span id="running-time">5</span> second <br/><br/>
					<center><img src="<?php echo $js_base_url ?>nicepay/load.gif" width="50%"></center>
					<br/><br/>
					<div style="color: red; font-weight: bold;">DO NOT CLOSE THIS WINDOW</div>
				</div>
			</td>
		</tr>
	</table>
</div>
<form name="redirectForm" action="<?php echo $return_base_url; ?>" method="GET">
	<input type="hidden" name="tXid" value="<?php echo $tXid; ?>" readonly />
</form>
<script>
	setInterval(function(){
		var time = document.getElementById("running-time").innerHTML;
		time = parseInt(time) - 1;
		if(time >= 0){
			document.getElementById("running-time").innerHTML = time;
		}
	}, 1000);
	setTimeout(function(){
		window.redirectForm.submit();
	}, 5000);
</script>
<?php
?>
